### ISSUE TITLE
Binary Search Tree

### ISSUE THREAD

**Issue by sudhanshupatel-dev** [ahampriyanshu/algo_ds_101#1724] opened 2021-10-03 07:54 UTC
### Type

Algorithm

### Directory

Algorithm => Searching => Binary_Search

### Description

Binary Search Tree is a node-based binary tree data structure which has the following properties -
1. The left subtree of a node contains only nodes with keys lesser than the node’s key.
2. The right subtree of a node contains only nodes with keys greater than the node’s key.
3. The left and right subtree each must also be a binary search tree.

### Programming Language

- [x] c++
- [ ] c
- [X] python
- [x] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by Jibendu007** [comment] 2021-10-03 08:01
@sudhanshupatel-dev can I be assigned to this?

**Comment by aditi830** [comment] 2021-10-03 08:16
assign me ,i will do in c++

**Comment by ZohaibSoomro** [comment] 2021-10-03 08:24
Assign it to me Sir i can do it in java

**Comment by kartik-ey1** [comment] 2021-10-03 09:22
sir i can do it as well 
please assign me

**Comment by MojoAlpha** [comment] 2021-10-03 09:46
assign me i can implement it in c

**Comment by hd2342-dubey** [comment] 2021-10-03 10:11
Please assign it to me in C++ I will do it

**Comment by ahampriyanshu** [comment] 2021-10-03 10:43
Duplicate of #498
![Screenshot from 2021-10-03 16-12-54](https://user-images.githubusercontent.com/54521023/135750165-a823d306-9607-463c-ad0f-d38d9eec0876.png)

**Closed by ahampriyanshu** 2021-10-03 10:43 UTC
Labels: good first issue, Hacktoberfest, first timer
