### ISSUE TITLE
Tower-of-Hanoi

### ISSUE THREAD

**Issue by sudhanshupatel-dev** [ahampriyanshu/algo_ds_101#1723] opened 2021-10-03 07:49 UTC
### Type

Algorithm

### Directory

Algorithm => Recursion => Tower-of-Hanoi.py

### Description

One of the most popular problem of all time tower of hanoi

### Programming Language

- [ ] c++
- [ ] c
- [X] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by sudhanshupatel-dev** [comment] 2021-10-03 07:52
@ahampriyanshu assign me this in python please.

**Comment by sarthakdelori** [comment] 2021-10-03 07:53
Assign me this in C++.

**Comment by ahampriyanshu** [comment] 2021-10-03 08:25
duplicate of #697, #1707 and #1706 !
Please follow contributing guidelines.

**Closed by ahampriyanshu** 2021-10-03 08:25 UTC
Labels: good first issue, Hacktoberfest, first timer
