### ISSUE TITLE
Tower of HANOI in using C++

### ISSUE THREAD

**Issue by andianiputri** [ahampriyanshu/algo_ds_101#1707] opened 2021-10-03 02:27 UTC
### Type

Algorithm

### Directory

Algorithm =>Tower of HANOI in using C++=>Tower of HANOI in using C++.extension

### Description

The Tower of Hanoi is a mathematical puzzle invented by the French mathematician Edouard Lucas in 1883.

There are three pegs, source(A), Auxiliary (B) and Destination(C). Peg A contains a set of disks stacked to resemble a tower, with the largest disk at the bottom and the smallest disk at the top. figure 1 Illustrate the initial configuration of the pegs for 3 disks. The objective is to transfer the entire tower of disks in peg A to peg C maintaining the same order of the disks.

### Programming Language

- [X] c++
- [X] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [X] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by andianiputri** [comment] 2021-10-03 02:28
yasss

**Comment by nishantkumar1308** [comment] 2021-10-03 02:32
Assign this to me

**Comment by rohitkumar9710** [comment] 2021-10-03 03:32
@andianiputri  Assign this to me in C++,C.

**Comment by ahampriyanshu** [comment] 2021-10-03 03:39
duplicate of #697

**Closed by ahampriyanshu** 2021-10-03 03:39 UTC
Labels: good first issue, Hacktoberfest, first timer
