### ISSUE TITLE
Trapping_water_collection

### ISSUE THREAD

**Issue by misrapk** [ahampriyanshu/algo_ds_101#1870] opened 2021-10-04 18:27 UTC
### Type

Algorithm

### Directory

Algorithms=>Array-Algorithm=>trappingRainwater.cpp

### Description

Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it is able to trap after raining.

Famous Basic level DSA array question.

### Programming Language

- [X] c++
- [X] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [X] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by misrapk** [comment] 2021-10-04 18:28
CPP => 1 hr

**Comment by Rohitshailesh43** [comment] 2021-10-04 18:40
python =>1hr

**Comment by ahampriyanshu** [comment] 2021-10-04 18:49
Duplicate of #1812  and #1809.

**Closed by ahampriyanshu** 2021-10-04 18:49 UTC
Labels: good first issue, Hacktoberfest, first timer
