### ISSUE TITLE
AVL tree insertion and deletion cpp program

### ISSUE THREAD

**Issue by SaahilSabu** [ahampriyanshu/algo_ds_101#1638] opened 2021-10-02 12:59 UTC
### Type

Algorithm

### Directory

algo_ds_101=>Algorithms=>Graph-Algorithms

### Description

AVL tree insertion and deletion cpp program

### Programming Language

- [X] c++
- [X] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by ahampriyanshu** [comment] 2021-10-02 13:11
duplicate of #489

**Closed by ahampriyanshu** 2021-10-02 13:11 UTC
Labels: good first issue, Hacktoberfest, first timer, python, java, javascript, go, typescript, scala, ruby, php, swift, haskell, bash, c++, c, c#

**Comment by prinsusinghal** [comment] 2021-10-02 13:25
@ahampriyanshu  Assign this to me for JAVA language.
