### ISSUE TITLE
Factorial Of A Number

### ISSUE THREAD

**Issue by thainapires** [ahampriyanshu/algo_ds_101#1027] opened 2020-10-07 22:10 UTC
**Submission Title**
Factorial Recursive Algorithm

**Submission Type**
Algorithm

**Submission Description**
A recursive algoritmn that calculates the factorial of a positive integer n, detoned by n!, that is the product of all positive integers less than or equal to n. 

**Submission Directory**
Maths_And_Stats => Algebra => Factorial =>  Factorial.py

**Contributors**

- [x]  C++ -
- [x]  C -
- [x]  Python -
- [x] Java - 
- [x] JavaScript -
- [x] TypeScript -
- [x] Golang -
- [x] Ruby -
- [x] php -
- [x] Swift -
- [x] C# -

**Comment by thainapires** [comment] 2020-10-07 22:11
Can you assign me for python?

**Comment by mhechavarria** [comment] 2020-10-07 23:23
Can you assign me for JS pleass?

**Comment by kcirym10** [comment] 2020-10-07 23:24
Could I please be assigned to the C++ and/or C versions

**Comment by thepoppycat** [comment] 2020-10-08 01:46
May I please be assigned to the Python version?

**Comment by thepoppycat** [comment] 2020-10-08 02:12
Apologies, could I please the assigned the golang one instead?

**Comment by jmiguelpv** [comment] 2020-10-08 02:31
Hi! can you assign me for PHP version?

**Comment by superconscript** [comment] 2020-10-08 02:45
Hi can you assign me the c++ version, I've completed my implementation, how do I submit it? Thank you.

**Comment by Procoder16** [comment] 2020-10-08 03:13
@thainapires ma'am, I have added the factorial recursive algorithm using C++. 

Kindly review it and notify me if any change is required or else if it matches the requirements of this repo, then kindly merge it to the main branch.

Thank You

**Comment by rebelfire888** [comment] 2020-10-08 05:02
Please Assign This To Me In C language.

**Comment by GerardoUbuntu** [comment] 2020-10-08 05:16
I want to do it in TypeScript

**Comment by thainapires** [comment] 2020-10-08 05:25
> @thainapires ma'am, I have added the factorial recursive algorithm using C++.
> 
> Kindly review it and notify me if any change is required or else if it matches the requirements of this repo, then kindly merge it to the main branch.
> 
> Thank You

Hi! Am I the one that has to assign? I'm new to the open source world, and I can't seen to find a place where I can assign everyone that is asking here. If someone could help me, it would be great! 😊

**Comment by rebelfire888** [comment] 2020-10-08 05:29
@thainapires Yes Maam you have to assign Us The Tasks.

**Comment by Procoder16** [comment] 2020-10-08 05:30
@thainapires you can directly merge the PRs also if you want

**Comment by Arsenic-ATG** [comment] 2020-10-08 06:00
@thainapires , you can't 
the power of merging PRs and assigning people to an issue is only in the hands of repository managers.

**Comment by Kadermiyanyedi** [comment] 2020-10-08 06:34
I want to do it in c# and golang

**Comment by Aditya489** [comment] 2020-10-08 10:45
i want to do it in ruby and javascript can you assign me in this?

**Comment by viveksahu26** [comment] 2020-10-08 14:17
Hey @thainapires , i would like to  work with this issue on Golang.  Can you assign me.

**Comment by neha07kumari** [comment] 2020-10-08 15:09
Please assign me in Golang. @ahampriyanshu

**Comment by aakashsoni-cloud** [comment] 2020-10-08 15:28
Please assign me in Python @ahampriyanshu

**Comment by appsx13** [comment] 2020-10-08 15:57
Can i go for javascript ?

**Comment by rgarg-2711** [comment] 2020-10-08 18:16
can you please assign this to me?

**Comment by adaugochi** [comment] 2020-10-08 20:34
Hi, I will like to do this in PHP. Can you please assign this to me

**Comment by ahampriyanshu** [comment] 2020-10-09 04:03
> can you please assign this to me?

Hi @rgarg-2711 :wave: ,
As of now, only **swift** implementation is left.
So, if you are familiar with swift , go ahead. (I'm closing this issue but you can still make a PR)

**Comment by ahampriyanshu** [comment] 2020-10-09 04:03
Thanks everyone :v:

**Closed by ahampriyanshu** 2020-10-09 04:03 UTC
Labels: C#, C++, Hacktoberfest, New Submssion, TypeScript, first timer, good first issue, java, javascript, php, python, ruby, scala, swift

**Comment by ahampriyanshu** [comment] 2020-10-09 04:15
``Duplicate of #279 but still some PRs(that offers better code quality) have been merged  ``
Hi @thainapires :wave: ,
You can use the **search-bar** or **#** to search for a pre-existing issue  before opening a new one :smile:

**Comment by thainapires** [comment] 2020-10-09 16:25
> `Duplicate of #279 but still some PRs(that offers better code quality) have been merged `
> Hi @thainapires 👋 ,
> You can use the **search-bar** or **#** to search for a pre-existing issue before opening a new one 😄

Oh Sorry! I'm new to this, but thanks for letting me know. Next time I'll search it better 😄

**Comment by neha07kumari** [comment] 2020-10-09 18:11
> Please assign me in Golang. @ahampriyanshu

Done
