### ISSUE TITLE
Rotate a matrix by 90 degree in clockwise direction

### ISSUE THREAD

**Issue by tanuj1811** [ahampriyanshu/algo_ds_101#1849] opened 2021-10-04 17:02 UTC
### Type

Algorithm

### Directory

Algorithms => Matrix-Algorithm

### Description

Get a square matrix, turn it by 90 degrees in a clockwise direction.

### Programming Language

- [ ] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by ahampriyanshu** [comment] 2021-10-04 17:03
duplicate of #1848

**Closed by ahampriyanshu** 2021-10-04 17:03 UTC
Labels: good first issue, Hacktoberfest, first timer
