### ISSUE TITLE
Largest Sum Contiguous Subarray (Kadane’s Algorithm)

### ISSUE THREAD

**Issue by Upasana9** [ahampriyanshu/algo_ds_101#852] opened 2020-10-06 05:35 UTC
**Submission Title**
Largest Sum Contiguous Subarray

**Submission Type**
Algorithm

**Submission Description**
Program to find the sum of contiguous subarray within a one-dimensional array of numbers which has the largest sum.

**Submission Directory**
Algorithm => Dynamic_Programming =>Largest_Sum_Contiguous_Subarray=> ... => LSCS.extension

**Contributors**

- [x]  C++ -
- [ ]  C -
- [x]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by guygreenleaf** [comment] 2020-10-06 06:18
Hello, 

Not sure what this issue is asking. The title leads me to believe the problem is to find the largest contiguous subarray.  
I can handle this recursively in C++ if you'd like to assign me to it.

**Comment by Nirali0029** [comment] 2020-10-06 07:02
I would like to do this for python.

**Comment by guygreenleaf** [comment] 2020-10-06 08:14
Hello, can you please add the Largest_Sum_Contiguous_Subarray folder inside the Dynamic Programming folder so I can submit a PR? 

Thanks!

**Comment by p-davide** [comment] 2020-10-06 10:48
I'd like to do this in C.

**Comment by Arsenic-ATG** [comment] 2020-10-06 11:09
I would like to do this for Swift.

**Comment by chinmaym07** [comment] 2020-10-06 11:44
Please assign this to me in java.

**Comment by keshari777** [comment] 2020-10-06 13:08
I would like to contribute to java

**Comment by Kishore-abhimanyu** [comment] 2020-10-06 16:45
I would like to work on it. Can you please assign me to this?

**Comment by varad64** [comment] 2020-10-07 02:30
I would like to work on it using Java. Could you please assign it to me?

**Comment by shadab-me** [comment] 2020-10-07 02:37
Done In JavaScript.

**Comment by Kunal2007** [comment] 2020-10-07 07:37
I would like to do it with C++. Please assign it to me.

**Comment by hello-fri-end** [comment] 2020-10-07 07:42
I implemented it in C++

**Comment by hello-fri-end** [comment] 2020-10-07 08:22
@Vimlesh-Kumar :Already done. I have submitted a pull request as well.

**Comment by hello-fri-end** [comment] 2020-10-07 10:57
@Vimlesh-Kumar : Is there any issue with my implementation? Why wasn't it merged?

**Comment by deepanshuoct12** [comment] 2020-10-07 11:14
I would like to work on this in C++. Can you please assign it to me?

**Comment by Rudransh24** [comment] 2020-10-08 17:38
Hello! Can you please assign this to me in C??

**Comment by rgarg-2711** [comment] 2020-10-08 18:17
can you please assign this to me?

**Comment by ahampriyanshu** [comment] 2020-10-11 21:14
thanks everyone :v:

**Closed by ahampriyanshu** 2020-10-11 21:14 UTC
Labels: C#, C++, Hacktoberfest, New Submssion, TypeScript, first timer, good first issue, java, javascript, php, ruby, scala, swift
